import 'package:kick26/src/common/image_paths.dart';

final List<Map<String, dynamic>> dummyCard = [
  // Trent Alexander-Arnold
  {
    "id": "UUID_TRENT",
    "data": {
      "edition": "2024",
      "totalIssued": 100,
      "sequenceNumber": 1,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-12-12T10:15:30Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "1234567890",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_TRENT",
      "name": "Trent Alexander-Arnold",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "RB",
        "age": 25,
        "height": 175,
        "weight": 69,
        "games": 320,
        "goals": 18,
        "assists": 81,
      },
    },
    "club": {"id": "123456789", "name": "Liverpool", "country": "GB", "city": "Liverpool"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.trent,
        "playerCard": "cdn/player/trent_card.png",
        "clubImage": ImagePaths.home.liverpool,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/trent_goals.mp4"},
    },
    "market": {
      "currentPrice": 105.0,
      "lastTransactionPrice": 102.5,
      "low": 98.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 4.25,
      "isUp": true,
      "floorPrice": 98.0,
      "highestBid": 104.25,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-14T09:30:00Z",
    },
    "transactions": [
      {
        "transactionType": "mint",
        "timestamp": "2024-12-12T10:15:30Z",
        "price": 100.0,
        "priceDelta": 0,
        "seller": {"id": "KICK26_PLATFORM", "name": "Kick26 Official", "icon": "cdn/platform.png"},
        "buyer": {"id": "USER_47211", "name": "Jan Goed", "icon": "cdn/user/jan.png"},
      },
      {
        "transactionType": "sale",
        "timestamp": "2024-12-15T14:20:00Z",
        "price": 98.5,
        "priceDelta": -1.1,
        "seller": {"id": "USER_89342", "name": "Alex Morgan", "icon": "cdn/user/alex.png"},
        "buyer": {"id": "USER_47211", "name": "Jan Goed", "icon": "cdn/user/jan.png"},
      },
    ],
    "metadata": {
      "card": {"rarity": 2.3, "popularity": 4.9},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Kylian Mbappé
  {
    "id": "UUID_MBAPPE",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 1,
      "class": "S",
      "type": "gold",
      "issuedAt": "2024-12-12T10:15:30Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "1234567890",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_MBAPPE",
      "name": "Kylian Mbappé",
      "countryCode": "FR",
      "snapshotBio": {
        "position": "FW",
        "age": 25,
        "height": 178,
        "weight": 75,
        "games": 350,
        "goals": 270,
        "assists": 110,
      },
    },
    "club": {"id": "REAL_MADRID", "name": "Real Madrid", "country": "ES", "city": "Madrid"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.mbappe,
        "playerCard": "cdn/player/trent_card.png",
        "clubImage": ImagePaths.home.realMadrid,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/trent_goals.mp4"},
    },
    "market": {
      "currentPrice": 190.0,
      "lastTransactionPrice": 102.5,
      "low": 98.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 42.35,
      "isUp": true,
      "floorPrice": 98.0,
      "highestBid": 104.25,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-14T09:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 4.9, "popularity": 5.0},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Viktor Gyökeres
  {
    "id": "UUID_GYOKERES",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 1,
      "class": "B",
      "type": "silver",
      "issuedAt": "2024-12-12T10:15:30Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "1234567890",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_GYOKERES",
      "name": "Viktor Gyökeres",
      "countryCode": "SE",
      "snapshotBio": {
        "position": "ST",
        "age": 26,
        "height": 187,
        "weight": 86,
        "games": 240,
        "goals": 105,
        "assists": 40,
      },
    },
    "club": {"id": "SPORTING_CP", "name": "Sporting CP", "country": "PT", "city": "Lisbon"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.gyokeres,
        "playerCard": "cdn/player/trent_card.png",
        "clubImage": ImagePaths.home.sporting,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/trent_goals.mp4"},
    },
    "market": {
      "currentPrice": 115.0,
      "lastTransactionPrice": 102.5,
      "low": 98.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 3.12,
      "isUp": true,
      "floorPrice": 98.0,
      "highestBid": 104.25,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-14T09:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 2.8, "popularity": 3.4},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Julián Álvarez
  {
    "id": "UUID_ALVAREZ",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 1,
      "class": "A",
      "type": "platinum",
      "issuedAt": "2024-12-12T10:15:30Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "1234567890",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_ALVAREZ",
      "name": "Julián Álvarez",
      "countryCode": "AR",
      "snapshotBio": {
        "position": "FW",
        "age": 24,
        "height": 170,
        "weight": 71,
        "games": 210,
        "goals": 92,
        "assists": 35,
      },
    },
    "club": {"id": "MAN_CITY", "name": "Manchester City", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.alvarez,
        "playerCard": "cdn/player/trent_card.png",
        "clubImage": ImagePaths.home.manchesterCity,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/trent_goals.mp4"},
    },
    "market": {
      "currentPrice": 120.0,
      "lastTransactionPrice": 102.5,
      "low": 98.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 7.45,
      "isUp": true,
      "floorPrice": 98.0,
      "highestBid": 104.25,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-14T09:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.9, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Erling Haaland
  {
    "id": "UUID_HAALAND",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 1,
      "class": "S",
      "type": "gold",
      "issuedAt": "2024-12-12T10:15:30Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "1234567890",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_HAALAND",
      "name": "Erling Haaland",
      "countryCode": "NO",
      "snapshotBio": {
        "position": "ST",
        "age": 24,
        "height": 194,
        "weight": 94,
        "games": 240,
        "goals": 210,
        "assists": 45,
      },
    },
    "club": {"id": "MAN_CITY", "name": "Manchester City", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.haaland,
        "playerCard": "cdn/player/trent_card.png",
        "clubImage": ImagePaths.home.manchesterCity,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/trent_goals.mp4"},
    },
    "market": {
      "currentPrice": 185.0,
      "lastTransactionPrice": 102.5,
      "low": 98.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 18.22,
      "isUp": true,
      "floorPrice": 98.0,
      "highestBid": 104.25,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-14T09:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 4.8, "popularity": 4.9},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Vinícius Jr
  {
    "id": "UUID_VINICIUS",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 12,
      "type": "platinum",
      "class": "A",
      "issuedAt": "2024-12-10T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_01",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_VINICIUS",
      "name": "Vinícius Jr",
      "countryCode": "BR",
      "snapshotBio": {
        "position": "LW",
        "age": 23,
        "height": 176,
        "weight": 73,
        "games": 260,
        "goals": 75,
        "assists": 70,
      },
    },
    "club": {"id": "REAL_MADRID", "name": "Real Madrid", "country": "ES", "city": "Madrid"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.vinicius,
        "playerCard": "cdn/player/vinicius_card.png",
        "clubImage": ImagePaths.home.realMadrid,
        "clubLogo": "cdn/club/real_madrid_logo.png",
      },
      "videos": {"goals": "cdn/video/vinicius_goals.mp4"},
    },
    "market": {
      "currentPrice": 155.0,
      "lastTransactionPrice": 148.5,
      "low": 145.0,
      "high": 160.0,
      "currency": "EUR",
      "trend": 15.67,
      "isUp": true,
      "floorPrice": 140.0,
      "highestBid": 152.0,
      "totalTrades": 8,
      "uniqueOwners": 6,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-20T11:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.8, "popularity": 4.6},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Bukayo Saka
  {
    "id": "UUID_SAKA",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 34,
      "type": "platinum",
      "class": "A",
      "issuedAt": "2024-12-11T10:45:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_01",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_SAKA",
      "name": "Bukayo Saka",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "RW",
        "age": 22,
        "height": 178,
        "weight": 72,
        "games": 220,
        "goals": 58,
        "assists": 51,
      },
    },
    "club": {"id": "ARSENAL", "name": "Arsenal", "country": "GB", "city": "London"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.saka,
        "playerCard": "cdn/player/saka_card.png",
        "clubImage": ImagePaths.home.arsenal,
        "clubLogo": "cdn/club/arsenal_logo.png",
      },
      "videos": {"goals": "cdn/video/saka_goals.mp4"},
    },
    "market": {
      "currentPrice": 145.0,
      "lastTransactionPrice": 139.0,
      "low": 135.0,
      "high": 150.0,
      "currency": "EUR",
      "trend": 12.85,
      "isUp": true,
      "floorPrice": 130.0,
      "highestBid": 142.0,
      "totalTrades": 6,
      "uniqueOwners": 5,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-18T15:10:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.6, "popularity": 4.4},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Pedri González
  {
    "id": "UUID_PEDRI",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 56,
      "type": "platinum",
      "class": "A",
      "issuedAt": "2024-12-09T08:30:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_02",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_PEDRI",
      "name": "Pedri González",
      "countryCode": "ES",
      "snapshotBio": {
        "position": "CM",
        "age": 21,
        "height": 174,
        "weight": 62,
        "games": 160,
        "goals": 18,
        "assists": 20,
      },
    },
    "club": {"id": "FCB", "name": "FC Barcelona", "country": "ES", "city": "Barcelona"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.pedri,
        "playerCard": "cdn/player/saka_card.png",
        "clubImage": ImagePaths.home.fcb,
        "clubLogo": "cdn/club/arsenal_logo.png",
      },
      "videos": {"goals": "cdn/video/saka_goals.mp4"},
    },
    "market": {
      "currentPrice": 125.0,
      "lastTransactionPrice": 128.0,
      "low": 120.0,
      "high": 135.0,
      "currency": "EUR",
      "trend": -2.15,
      "isUp": false,
      "floorPrice": 118.0,
      "highestBid": 124.0,
      "totalTrades": 4,
      "uniqueOwners": 4,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-10T10:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.4, "popularity": 4.1},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Florian Wirtz
  {
    "id": "UUID_WIRTZ",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 78,
      "type": "platinum",
      "class": "A",
      "issuedAt": "2024-12-08T12:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_02",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_WIRTZ",
      "name": "Florian Wirtz",
      "countryCode": "DE",
      "snapshotBio": {
        "position": "AM",
        "age": 21,
        "height": 176,
        "weight": 70,
        "games": 150,
        "goals": 35,
        "assists": 40,
      },
    },
    "club": {"id": "LEVERKUSEN", "name": "Bayer Leverkusen", "country": "DE", "city": "Leverkusen"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.wirtz,
        "playerCard": "cdn/player/saka_card.png",
        "clubImage": ImagePaths.home.leverkusen,
        "clubLogo": "cdn/club/arsenal_logo.png",
      },
      "videos": {"goals": "cdn/video/saka_goals.mp4"},
    },
    "market": {
      "currentPrice": 150.0,
      "lastTransactionPrice": 102.5,
      "low": 98.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 9.48,
      "isUp": true,
      "floorPrice": 98.0,
      "highestBid": 104.25,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-14T09:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.7, "popularity": 4.2},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Jude Bellingham
  {
    "id": "UUID_BELLINGHAM",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 5,
      "type": "gold",
      "class": "S",
      "issuedAt": "2024-12-07T14:20:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_01",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_BELLINGHAM",
      "name": "Jude Bellingham",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "CM",
        "age": 21,
        "height": 186,
        "weight": 75,
        "games": 200,
        "goals": 55,
        "assists": 30,
      },
    },
    "club": {"id": "REAL_MADRID", "name": "Real Madrid", "country": "ES", "city": "Madrid"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.bellingham,
        "playerCard": "cdn/player/saka_card.png",
        "clubImage": ImagePaths.home.realMadrid,
        "clubLogo": "cdn/club/arsenal_logo.png",
      },
      "videos": {"goals": "cdn/video/saka_goals.mp4"},
    },
    "market": {
      "currentPrice": 180.0,
      "lastTransactionPrice": 102.5,
      "low": 98.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 25.75,
      "isUp": true,
      "floorPrice": 98.0,
      "highestBid": 104.25,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-14T09:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 4.9, "popularity": 5.0},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Phil Foden
  {
    "id": "UUID_FODEN",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 14,
      "type": "gold",
      "class": "A",
      "issuedAt": "2024-11-20T09:10:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_01",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_FODEN",
      "name": "Phil Foden",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "AM",
        "age": 23,
        "height": 171,
        "weight": 70,
        "games": 260,
        "goals": 65,
        "assists": 45,
      },
    },
    "club": {"id": "MAN_CITY", "name": "Manchester City", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.foden,
        "playerCard": "cdn/player/foden_card.png",
        "clubImage": ImagePaths.home.manchesterCity,
        "clubLogo": "cdn/club/mancity_logo.png",
      },
      "videos": {"goals": "cdn/video/foden_goals.mp4"},
    },
    "market": {
      "currentPrice": 135.0,
      "lastTransactionPrice": 130.5,
      "low": 128.0,
      "high": 138.0,
      "currency": "EUR",
      "trend": 10.25,
      "isUp": true,
      "floorPrice": 128.0,
      "highestBid": 134.5,
      "totalTrades": 6,
      "uniqueOwners": 5,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-18T12:40:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.8, "popularity": 4.6},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Lautaro Martínez
  {
    "id": "UUID_LAUTARO",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 87,
      "type": "gold",
      "class": "A",
      "issuedAt": "2024-10-05T11:30:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_02",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_LAUTARO",
      "name": "Lautaro Martínez",
      "countryCode": "AR",
      "snapshotBio": {
        "position": "ST",
        "age": 26,
        "height": 174,
        "weight": 72,
        "games": 280,
        "goals": 150,
        "assists": 50,
      },
    },
    "club": {"id": "INTER", "name": "Inter Milan", "country": "IT", "city": "Milan"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.martinez,
        "playerCard": "cdn/player/lautaro_card.png",
        "clubImage": ImagePaths.home.inter,
        "clubLogo": "cdn/club/inter_logo.png",
      },
      "videos": {"goals": "cdn/video/lautaro_goals.mp4"},
    },
    "market": {
      "currentPrice": 125.0,
      "lastTransactionPrice": 122.0,
      "low": 118.0,
      "high": 126.0,
      "currency": "EUR",
      "trend": 6.52,
      "isUp": true,
      "floorPrice": 118.0,
      "highestBid": 124.2,
      "totalTrades": 8,
      "uniqueOwners": 7,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-12T15:05:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.6, "popularity": 4.4},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Khvicha Kvaratskhelia
  {
    "id": "UUID_KVARA",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 203,
      "type": "gold",
      "class": "A",
      "issuedAt": "2024-09-12T08:45:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_03",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_KVARA",
      "name": "Khvicha Kvaratskhelia",
      "countryCode": "GE",
      "snapshotBio": {
        "position": "LW",
        "age": 23,
        "height": 183,
        "weight": 76,
        "games": 170,
        "goals": 45,
        "assists": 50,
      },
    },
    "club": {"id": "CLUB_NAPOLI", "name": "Napoli", "country": "IT", "city": "Naples"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.kvaratskhelia,
        "playerCard": "cdn/player/kvara_card.png",
        "clubImage": ImagePaths.home.napoli,
        "clubLogo": "cdn/club/napoli_logo.png",
      },
      "videos": {"goals": "cdn/video/kvara_goals.mp4"},
    },
    "market": {
      "currentPrice": 140.0,
      "lastTransactionPrice": 142.5,
      "low": 138.0,
      "high": 150.0,
      "currency": "EUR",
      "trend": -1.84,
      "isUp": false,
      "floorPrice": 138.0,
      "highestBid": 139.0,
      "totalTrades": 4,
      "uniqueOwners": 4,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-09T18:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.7, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Rafael Leão
  {
    "id": "UUID_LEAO",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 311,
      "type": "gold",
      "class": "A",
      "issuedAt": "2024-08-28T10:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_04",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_LEAO",
      "name": "Rafael Leão",
      "countryCode": "PT",
      "snapshotBio": {
        "position": "LW",
        "age": 24,
        "height": 188,
        "weight": 81,
        "games": 240,
        "goals": 65,
        "assists": 55,
      },
    },
    "club": {"id": "CLUB_MILAN", "name": "AC Milan", "country": "IT", "city": "Milan"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.leao,
        "playerCard": "cdn/player/leao_card.png",
        "clubImage": ImagePaths.home.milan,
        "clubLogo": "cdn/club/milan_logo.png",
      },
      "videos": {"goals": "cdn/video/leao_goals.mp4"},
    },
    "market": {
      "currentPrice": 130.0,
      "lastTransactionPrice": 126.0,
      "low": 124.0,
      "high": 132.0,
      "currency": "EUR",
      "trend": 8.35,
      "isUp": true,
      "floorPrice": 124.0,
      "highestBid": 129.8,
      "totalTrades": 7,
      "uniqueOwners": 6,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T17:10:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.5, "popularity": 4.2},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Jamal Musiala
  {
    "id": "UUID_MUSIALA",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 5,
      "type": "gold",
      "class": "S",
      "issuedAt": "2024-12-01T07:20:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_05",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_MUSIALA",
      "name": "Jamal Musiala",
      "countryCode": "DE",
      "snapshotBio": {
        "position": "AM",
        "age": 21,
        "height": 183,
        "weight": 70,
        "games": 170,
        "goals": 40,
        "assists": 30,
      },
    },
    "club": {"id": "CLUB_BAYERN", "name": "Bayern Munich", "country": "DE", "city": "Munich"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.musiala,
        "playerCard": "cdn/player/musiala_card.png",
        "clubImage": ImagePaths.home.bayern,
        "clubLogo": "cdn/club/bayern_logo.png",
      },
      "videos": {"goals": "cdn/video/musiala_goals.mp4"},
    },
    "market": {
      "currentPrice": 165.0,
      "lastTransactionPrice": 160.0,
      "low": 155.0,
      "high": 170.0,
      "currency": "EUR",
      "trend": 6.72,
      "isUp": true,
      "floorPrice": 155.0,
      "highestBid": 164.8,
      "totalTrades": 10,
      "uniqueOwners": 8,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-02-02T11:55:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 4.6, "popularity": 4.9},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Rodrygo Goes
  {
    "id": "UUID_RODRYGO",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 42,
      "type": "gold",
      "class": "A",
      "issuedAt": "2024-10-18T08:30:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_06",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_RODRYGO",
      "name": "Rodrygo Goes",
      "countryCode": "BR",
      "snapshotBio": {
        "position": "RW",
        "age": 23,
        "height": 174,
        "weight": 70,
        "games": 210,
        "goals": 48,
        "assists": 35,
      },
    },
    "club": {"id": "CLUB_REAL", "name": "Real Madrid", "country": "ES", "city": "Madrid"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.rodrygo,
        "playerCard": "cdn/player/rodrygo_card.png",
        "clubImage": ImagePaths.home.realMadrid,
        "clubLogo": "cdn/club/real_madrid_logo.png",
      },
      "videos": {"goals": "cdn/video/rodrygo_goals.mp4"},
    },
    "market": {
      "currentPrice": 120.0,
      "lastTransactionPrice": 118.5,
      "low": 112.0,
      "high": 125.0,
      "currency": "EUR",
      "trend": 5.42,
      "isUp": true,
      "floorPrice": 112.0,
      "highestBid": 119.8,
      "totalTrades": 6,
      "uniqueOwners": 5,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-20T14:25:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.7, "popularity": 4.4},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Martin Ødegaard
  {
    "id": "UUID_ODEGAARD",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 19,
      "type": "gold",
      "class": "A",
      "issuedAt": "2024-11-05T10:45:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_07",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_ODEGAARD",
      "name": "Martin Ødegaard",
      "countryCode": "NO",
      "snapshotBio": {
        "position": "AM",
        "age": 25,
        "height": 178,
        "weight": 68,
        "games": 300,
        "goals": 70,
        "assists": 80,
      },
    },
    "club": {"id": "CLUB_ARSENAL", "name": "Arsenal", "country": "GB", "city": "London"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.odegaard,
        "playerCard": "cdn/player/odegaard_card.png",
        "clubImage": ImagePaths.home.arsenal,
        "clubLogo": "cdn/club/arsenal_logo.png",
      },
      "videos": {"goals": "cdn/video/odegaard_goals.mp4"},
    },
    "market": {
      "currentPrice": 135.0,
      "lastTransactionPrice": 131.0,
      "low": 128.0,
      "high": 138.0,
      "currency": "EUR",
      "trend": 9.64,
      "isUp": true,
      "floorPrice": 128.0,
      "highestBid": 134.7,
      "totalTrades": 9,
      "uniqueOwners": 7,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-28T16:40:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 4.0, "popularity": 4.7},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // João Félix
  {
    "id": "UUID_FELIX",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 214,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-09-02T07:15:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_08",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_FELIX",
      "name": "João Félix",
      "countryCode": "PT",
      "snapshotBio": {
        "position": "SS",
        "age": 24,
        "height": 181,
        "weight": 70,
        "games": 220,
        "goals": 60,
        "assists": 40,
      },
    },
    "club": {"id": "CLUB_FCB", "name": "FC Barcelona", "country": "ES", "city": "Barcelona"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.felix,
        "playerCard": "cdn/player/felix_card.png",
        "clubImage": ImagePaths.home.fcb,
        "clubLogo": "cdn/club/barcelona_logo.png",
      },
      "videos": {"goals": "cdn/video/felix_goals.mp4"},
    },
    "market": {
      "currentPrice": 95.0,
      "lastTransactionPrice": 99.0,
      "low": 92.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": -4.38,
      "isUp": false,
      "floorPrice": 92.0,
      "highestBid": 94.2,
      "totalTrades": 5,
      "uniqueOwners": 5,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-07T13:50:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 2.9, "popularity": 3.8},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Gavi
  {
    "id": "UUID_GAVI",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 301,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-10-01T06:50:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_09",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_GAVI",
      "name": "Gavi",
      "countryCode": "ES",
      "snapshotBio": {
        "position": "CM",
        "age": 20,
        "height": 173,
        "weight": 68,
        "games": 130,
        "goals": 10,
        "assists": 12,
      },
    },
    "club": {"id": "CLUB_FCB", "name": "FC Barcelona", "country": "ES", "city": "Barcelona"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.gavi,
        "playerCard": "cdn/player/gavi_card.png",
        "clubImage": ImagePaths.home.fcb,
        "clubLogo": "cdn/club/barcelona_logo.png",
      },
      "videos": {"goals": "cdn/video/gavi_goals.mp4"},
    },
    "market": {
      "currentPrice": 110.0,
      "lastTransactionPrice": 108.0,
      "low": 104.0,
      "high": 115.0,
      "currency": "EUR",
      "trend": 3.47,
      "isUp": true,
      "floorPrice": 104.0,
      "highestBid": 109.5,
      "totalTrades": 4,
      "uniqueOwners": 4,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-22T11:15:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.1, "popularity": 4.0},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Marcus Rashford
  {
    "id": "UUID_RASHFORD",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 412,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-08-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_10",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_RASHFORD",
      "name": "Marcus Rashford",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "LW",
        "age": 26,
        "height": 186,
        "weight": 78,
        "games": 370,
        "goals": 130,
        "assists": 70,
      },
    },
    "club": {"id": "CLUB_MU", "name": "Manchester United", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.rashford,
        "playerCard": "cdn/player/rashford_card.png",
        "clubImage": ImagePaths.home.manchesterUnited,
        "clubLogo": "cdn/club/manutd_logo.png",
      },
      "videos": {"goals": "cdn/video/rashford_goals.mp4"},
    },
    "market": {
      "currentPrice": 105.0,
      "lastTransactionPrice": 111.0,
      "low": 102.0,
      "high": 118.0,
      "currency": "EUR",
      "trend": -5.26,
      "isUp": false,
      "floorPrice": 102.0,
      "highestBid": 104.0,
      "totalTrades": 7,
      "uniqueOwners": 6,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-05T19:10:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.0, "popularity": 4.1},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Leroy Sané
  {
    "id": "UUID_SANE",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 123,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-09-01T06:50:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_11",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_SANE",
      "name": "Leroy Sané",
      "countryCode": "DE",
      "snapshotBio": {
        "position": "LW",
        "age": 28,
        "height": 183,
        "weight": 75,
        "games": 310,
        "goals": 90,
        "assists": 80,
      },
    },
    "club": {"id": "CLUB_BAY", "name": "Bayern Munich", "country": "DE", "city": "Munich"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.sane,
        "playerCard": "cdn/player/sane_card.png",
        "clubImage": ImagePaths.home.bayern,
        "clubLogo": "cdn/club/bayern_logo.png",
      },
      "videos": {"goals": "cdn/video/sane_goals.mp4"},
    },
    "market": {
      "currentPrice": 100.0,
      "lastTransactionPrice": 98.0,
      "low": 95.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 2.04,
      "isUp": true,
      "floorPrice": 95.0,
      "highestBid": 99.0,
      "totalTrades": 5,
      "uniqueOwners": 5,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-10T14:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Ferran Torres
  {
    "id": "UUID_TORRES",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 145,
      "type": "silver",
      "class": "C",
      "issuedAt": "2024-10-10T08:20:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_12",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_TORRES",
      "name": "Ferran Torres",
      "countryCode": "ES",
      "snapshotBio": {
        "position": "RW",
        "age": 24,
        "height": 184,
        "weight": 77,
        "games": 200,
        "goals": 43,
        "assists": 25,
      },
    },
    "club": {"id": "CLUB_FCB", "name": "FC Barcelona", "country": "ES", "city": "Barcelona"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.ferran,
        "playerCard": "cdn/player/torres_card.png",
        "clubImage": ImagePaths.home.fcb,
        "clubLogo": "cdn/club/barcelona_logo.png",
      },
      "videos": {"goals": "cdn/video/torres_goals.mp4"},
    },
    "market": {
      "currentPrice": 90.0,
      "lastTransactionPrice": 92.5,
      "low": 88.0,
      "high": 95.0,
      "currency": "EUR",
      "trend": -2.70,
      "isUp": false,
      "floorPrice": 88.0,
      "highestBid": 89.5,
      "totalTrades": 4,
      "uniqueOwners": 4,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T12:20:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Federico Valverde
  {
    "id": "UUID_VALVERDE",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 123,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-09-01T06:50:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_11",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_VALVERDE",
      "name": "Federico Valverde",
      "countryCode": "UY",
      "snapshotBio": {
        "position": "CM",
        "age": 25,
        "height": 182,
        "weight": 78,
        "games": 260,
        "goals": 32,
        "assists": 40,
      },
    },
    "club": {"id": "CLUB_REAL", "name": "Real Madrid", "country": "ES", "city": "Madrid"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.valverde,
        "playerCard": "cdn/player/valverde_card.png",
        "clubImage": ImagePaths.home.realMadrid,
        "clubLogo": "cdn/club/real_madrid_logo.png",
      },
      "videos": {"goals": "cdn/video/valverde_goals.mp4"},
    },
    "market": {
      "currentPrice": 145.0,
      "lastTransactionPrice": 140.0,
      "low": 135.0,
      "high": 150.0,
      "currency": "EUR",
      "trend": 8.12,
      "isUp": true,
      "floorPrice": 135.0,
      "highestBid": 140.0,
      "totalTrades": 5,
      "uniqueOwners": 5,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-10T14:30:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Declan Rice
  {
    "id": "UUID_RICE",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 145,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-10T08:20:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_12",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_RICE",
      "name": "Declan Rice",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "CDM",
        "age": 25,
        "height": 185,
        "weight": 80,
        "games": 300,
        "goals": 18,
        "assists": 20,
      },
    },
    "club": {"id": "CLUB_ARSENAL", "name": "Arsenal", "country": "GB", "city": "London"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.rice,
        "playerCard": "cdn/player/rice_card.png",
        "clubImage": ImagePaths.home.arsenal,
        "clubLogo": "cdn/club/arsenal_logo.png",
      },
      "videos": {"goals": "cdn/video/rice_goals.mp4"},
    },
    "market": {
      "currentPrice": 135.0,
      "lastTransactionPrice": 130.0,
      "low": 128.0,
      "high": 140.0,
      "currency": "EUR",
      "trend": 5.98,
      "isUp": true,
      "floorPrice": 128.0,
      "highestBid": 134.0,
      "totalTrades": 6,
      "uniqueOwners": 5,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-12T15:05:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Enzo Fernández
  {
    "id": "UUID_ENZO",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_ENZO",
      "name": "Enzo Fernández",
      "countryCode": "AR",
      "snapshotBio": {
        "position": "CM",
        "age": 23,
        "height": 178,
        "weight": 73,
        "games": 150,
        "goals": 12,
        "assists": 18,
      },
    },
    "club": {"id": "CLUB_CHELSEA", "name": "Chelsea", "country": "GB", "city": "London"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.enzo,
        "playerCard": "cdn/player/enzo_card.png",
        "clubImage": ImagePaths.home.chelsea,
        "clubLogo": "cdn/club/chelsea_logo.png",
      },
      "videos": {"goals": "cdn/video/enzo_goals.mp4"},
    },
    "market": {
      "currentPrice": 115.0,
      "lastTransactionPrice": 110.0,
      "low": 108.0,
      "high": 120.0,
      "currency": "EUR",
      "trend": -3.12,
      "isUp": false,
      "floorPrice": 108.0,
      "highestBid": 112.0,
      "totalTrades": 4,
      "uniqueOwners": 4,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Christopher Nkunku
  {
    "id": "UUID_NKUNKU",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_NKUNKU",
      "name": "Christopher Nkunku",
      "countryCode": "FR",
      "snapshotBio": {
        "position": "CAM",
        "age": 27,
        "height": 175,
        "weight": 69,
        "games": 260,
        "goals": 105,
        "assists": 60,
      },
    },
    "club": {"id": "CLUB_CHELSEA", "name": "Chelsea", "country": "GB", "city": "London"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.nkunku,
        "playerCard": "cdn/player/nkunku_card.png",
        "clubImage": ImagePaths.home.chelsea,
        "clubLogo": "cdn/club/chelsea_logo.png",
      },
      "videos": {"goals": "cdn/video/nkunku_goals.mp4"},
    },
    "market": {
      "currentPrice": 110.0,
      "lastTransactionPrice": 105.0,
      "low": 103.0,
      "high": 115.0,
      "currency": "EUR",
      "trend": 2.54,
      "isUp": true,
      "floorPrice": 103.0,
      "highestBid": 109.0,
      "totalTrades": 5,
      "uniqueOwners": 4,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Alejandro Garnacho
  {
    "id": "UUID_GARNACHO",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_GARNACHO",
      "name": "Alejandro Garnacho",
      "countryCode": "AR",
      "snapshotBio": {"position": "LW", "age": 19, "height": 175, "weight": 70, "games": 50, "goals": 10, "assists": 5},
    },
    "club": {"id": "CLUB_MANUTD", "name": "Manchester United", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.garnacho,
        "playerCard": "cdn/player/garnacho_card.png",
        "clubImage": ImagePaths.home.manchesterUnited,
        "clubLogo": "cdn/club/manutd_logo.png",
      },
      "videos": {"goals": "cdn/video/garnacho_goals.mp4"},
    },
    "market": {
      "currentPrice": 95.0,
      "lastTransactionPrice": 90.0,
      "low": 88.0,
      "high": 100.0,
      "currency": "EUR",
      "trend": 1.05,
      "isUp": true,
      "floorPrice": 88.0,
      "highestBid": 92.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Nico Williams
  {
    "id": "UUID_WILLIAMS",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_WILLIAMS",
      "name": "Nico Williams",
      "countryCode": "ES",
      "snapshotBio": {
        "position": "RW",
        "age": 21,
        "height": 181,
        "weight": 72,
        "games": 150,
        "goals": 25,
        "assists": 30,
      },
    },
    "club": {"id": "CLUB_BILBAO", "name": "Athletic Bilbao", "country": "ES", "city": "Bilbao"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.nico,
        "playerCard": "cdn/player/nico_card.png",
        "clubImage": ImagePaths.home.bilbao,
        "clubLogo": "cdn/club/bilbao_logo.png",
      },
      "videos": {"goals": "cdn/video/nico_goals.mp4"},
    },
    "market": {
      "currentPrice": 105.0,
      "lastTransactionPrice": 100.0,
      "low": 98.0,
      "high": 110.0,
      "currency": "EUR",
      "trend": 4.62,
      "isUp": true,
      "floorPrice": 98.0,
      "highestBid": 102.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Xavi Simons
  {
    "id": "UUID_SIMONS",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_SIMONS",
      "name": "Xavi Simons",
      "countryCode": "NL",
      "snapshotBio": {
        "position": "CAM",
        "age": 21,
        "height": 179,
        "weight": 71,
        "games": 120,
        "goals": 25,
        "assists": 35,
      },
    },
    "club": {"id": "CLUB_RBL", "name": "RB Leipzig", "country": "DE", "city": "Leipzig"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.simons,
        "playerCard": "cdn/player/simons_card.png",
        "clubImage": ImagePaths.home.rbl,
        "clubLogo": "cdn/club/rbl_logo.png",
      },
      "videos": {"goals": "cdn/video/simons_goals.mp4"},
    },
    "market": {
      "currentPrice": 120.0,
      "lastTransactionPrice": 115.0,
      "low": 113.0,
      "high": 125.0,
      "currency": "EUR",
      "trend": 12.38,
      "isUp": true,
      "floorPrice": 113.0,
      "highestBid": 118.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Rasmus Højlund
  {
    "id": "UUID_HOJLUND",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "C",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_HOJLUND",
      "name": "Rasmus Højlund",
      "countryCode": "DK",
      "snapshotBio": {
        "position": "ST",
        "age": 21,
        "height": 191,
        "weight": 84,
        "games": 110,
        "goals": 32,
        "assists": 10,
      },
    },
    "club": {"id": "CLUB_MANU", "name": "Manchester United", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.hojlund,
        "playerCard": "cdn/player/hojlund_card.png",
        "clubImage": ImagePaths.home.manchesterUnited,
        "clubLogo": "cdn/club/manchester_united_logo.png",
      },
      "videos": {"goals": "cdn/video/hojlund_goals.mp4"},
    },
    "market": {
      "currentPrice": 85.0,
      "lastTransactionPrice": 80.0,
      "low": 78.0,
      "high": 90.0,
      "currency": "EUR",
      "trend": 6.41,
      "isUp": true,
      "floorPrice": 78.0,
      "highestBid": 82.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Frenkie de Jong
  {
    "id": "UUID_DE_JONG",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_DE_JONG",
      "name": "Frenkie de Jong",
      "countryCode": "NL",
      "snapshotBio": {
        "position": "CM",
        "age": 27,
        "height": 181,
        "weight": 74,
        "games": 340,
        "goals": 23,
        "assists": 30,
      },
    },
    "club": {"id": "CLUB_FCB", "name": "FC Barcelona", "country": "ES", "city": "Barcelona"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.dejong,
        "playerCard": "cdn/player/dejong_card.png",
        "clubImage": ImagePaths.home.fcb,
        "clubLogo": "cdn/club/fcb_logo.png",
      },
      "videos": {"goals": "cdn/video/dejong_goals.mp4"},
    },
    "market": {
      "currentPrice": 125.0,
      "lastTransactionPrice": 120.0,
      "low": 118.0,
      "high": 130.0,
      "currency": "EUR",
      "trend": -1.92,
      "isUp": false,
      "floorPrice": 118.0,
      "highestBid": 122.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Joshua Kimmich
  {
    "id": "UUID_KIMMICH",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_KIMMICH",
      "name": "Joshua Kimmich",
      "countryCode": "DE",
      "snapshotBio": {
        "position": "CM",
        "age": 29,
        "height": 177,
        "weight": 72,
        "games": 410,
        "goals": 48,
        "assists": 90,
      },
    },
    "club": {"id": "CLUB_BAYERN", "name": "Bayern Munich", "country": "DE", "city": "Munich"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.kimmich,
        "playerCard": "cdn/player/kimmich_card.png",
        "clubImage": ImagePaths.home.bayern,
        "clubLogo": "cdn/club/bayern_logo.png",
      },
      "videos": {"goals": "cdn/video/kimmich_goals.mp4"},
    },
    "market": {
      "currentPrice": 130.0,
      "lastTransactionPrice": 125.0,
      "low": 120.0,
      "high": 140.0,
      "currency": "EUR",
      "trend": 2.73,
      "isUp": true,
      "floorPrice": 120.0,
      "highestBid": 128.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Casemiro
  {
    "id": "UUID_CASEMIRO",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_CASEMIRO",
      "name": "Casemiro",
      "countryCode": "BR",
      "snapshotBio": {
        "position": "CDM",
        "age": 32,
        "height": 185,
        "weight": 84,
        "games": 520,
        "goals": 55,
        "assists": 40,
      },
    },
    "club": {"id": "CLUB_MANU", "name": "Manchester United", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.casemiro,
        "playerCard": "cdn/player/casemiro_card.png",
        "clubImage": ImagePaths.home.manchesterUnited,
        "clubLogo": "cdn/club/manchester_united_logo.png",
      },
      "videos": {"goals": "cdn/video/casemiro_goals.mp4"},
    },
    "market": {
      "currentPrice": 95.0,
      "lastTransactionPrice": 90.0,
      "low": 88.0,
      "high": 100.0,
      "currency": "EUR",
      "trend": -3.88,
      "isUp": false,
      "floorPrice": 88.0,
      "highestBid": 92.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Sandro Tonali
  {
    "id": "UUID_TONALI",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_TONALI",
      "name": "Sandro Tonali",
      "countryCode": "IT",
      "snapshotBio": {
        "position": "CM",
        "age": 23,
        "height": 181,
        "weight": 79,
        "games": 210,
        "goals": 15,
        "assists": 22,
      },
    },
    "club": {"id": "CLUB_NEWCASTLE", "name": "Newcastle United", "country": "GB", "city": "Newcastle"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.tonali,
        "playerCard": "cdn/player/tonali_card.png",
        "clubImage": ImagePaths.home.newcastle,
        "clubLogo": "cdn/club/newcastle_logo.png",
      },
      "videos": {"goals": "cdn/video/tonali_goals.mp4"},
    },
    "market": {
      "currentPrice": 100.0,
      "lastTransactionPrice": 95.0,
      "low": 90.0,
      "high": 110.0,
      "currency": "EUR",
      "trend": -6.74,
      "isUp": false,
      "floorPrice": 90.0,
      "highestBid": 95.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Bernardo Silva
  {
    "id": "UUID_BERNARDO",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_BERNARDO",
      "name": "Bernardo Silva",
      "countryCode": "PT",
      "snapshotBio": {
        "position": "RW",
        "age": 29,
        "height": 173,
        "weight": 64,
        "games": 520,
        "goals": 80,
        "assists": 95,
      },
    },
    "club": {"id": "CLUB_MAN_CITY", "name": "Manchester City", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.bernardo,
        "playerCard": "cdn/player/bernardo_card.png",
        "clubImage": ImagePaths.home.manchesterCity,
        "clubLogo": "cdn/club/manchester_city_logo.png",
      },
      "videos": {"goals": "cdn/video/bernardo_goals.mp4"},
    },
    "market": {
      "currentPrice": 140.0,
      "lastTransactionPrice": 135.0,
      "low": 130.0,
      "high": 150.0,
      "currency": "EUR",
      "trend": 3.45,
      "isUp": true,
      "floorPrice": 130.0,
      "highestBid": 135.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Jack Grealish
  {
    "id": "UUID_GREALISH",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_GREALISH",
      "name": "Jack Grealish",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "LW",
        "age": 28,
        "height": 180,
        "weight": 75,
        "games": 340,
        "goals": 55,
        "assists": 50,
      },
    },
    "club": {"id": "CLUB_MAN_CITY", "name": "Manchester City", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.grealish,
        "playerCard": "cdn/player/grealish_card.png",
        "clubImage": ImagePaths.home.manchesterCity,
        "clubLogo": "cdn/club/manchester_city_logo.png",
      },
      "videos": {"goals": "cdn/video/grealish_goals.mp4"},
    },
    "market": {
      "currentPrice": 110.0,
      "lastTransactionPrice": 105.0,
      "low": 100.0,
      "high": 120.0,
      "currency": "EUR",
      "trend": -1.24,
      "isUp": false,
      "floorPrice": 100.0,
      "highestBid": 105.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Bruno Fernandes
  {
    "id": "UUID_FERNANDES",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 156,
      "type": "silver",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_13",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_FERNANDES",
      "name": "Bruno Fernandes",
      "countryCode": "PT",
      "snapshotBio": {
        "position": "CAM",
        "age": 29,
        "height": 179,
        "weight": 69,
        "games": 430,
        "goals": 135,
        "assists": 120,
      },
    },
    "club": {"id": "CLUB_MAN_UNITED", "name": "Manchester United", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.bruno,
        "playerCard": "cdn/player/fernandes_card.png",
        "clubImage": ImagePaths.home.manchesterUnited,
        "clubLogo": "cdn/club/manchester_united_logo.png",
      },
      "videos": {"goals": "cdn/video/fernandes_goals.mp4"},
    },
    "market": {
      "currentPrice": 120.0,
      "lastTransactionPrice": 115.0,
      "low": 110.0,
      "high": 130.0,
      "currency": "EUR",
      "trend": 5.26,
      "isUp": true,
      "floorPrice": 110.0,
      "highestBid": 115.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Mohamed Salah
  {
    "id": "UUID_SALAH",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 157,
      "type": "gold",
      "class": "S",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_14",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_SALAH",
      "name": "Mohamed Salah",
      "countryCode": "EG",
      "snapshotBio": {
        "position": "RW",
        "age": 32,
        "height": 175,
        "weight": 74,
        "games": 620,
        "goals": 290,
        "assists": 140,
      },
    },
    "club": {"id": "CLUB_LIVERPOOL", "name": "Liverpool", "country": "GB", "city": "Liverpool"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.salah,
        "playerCard": "cdn/player/salah_card.png",
        "clubImage": ImagePaths.home.liverpool,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/salah_goals.mp4"},
    },
    "market": {
      "currentPrice": 150.0,
      "lastTransactionPrice": 145.0,
      "low": 140.0,
      "high": 160.0,
      "currency": "EUR",
      "trend": 11.24,
      "isUp": true,
      "floorPrice": 140.0,
      "highestBid": 145.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Darwin Núñez
  {
    "id": "UUID_NUNEZ",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 158,
      "type": "bronze",
      "class": "C",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_15",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_NUNEZ",
      "name": "Darwin Núñez",
      "countryCode": "UY",
      "snapshotBio": {
        "position": "CF",
        "age": 25,
        "height": 187,
        "weight": 81,
        "games": 170,
        "goals": 70,
        "assists": 20,
      },
    },
    "club": {"id": "CLUB_LIVERPOOL", "name": "Liverpool", "country": "GB", "city": "Liverpool"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.nunez,
        "playerCard": "cdn/player/nunez_card.png",
        "clubImage": ImagePaths.home.liverpool,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/nunez_goals.mp4"},
    },
    "market": {
      "currentPrice": 85.0,
      "lastTransactionPrice": 80.0,
      "low": 75.0,
      "high": 90.0,
      "currency": "EUR",
      "trend": 3.15,
      "isUp": true,
      "floorPrice": 75.0,
      "highestBid": 80.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Son Heung-min
  {
    "id": "UUID_SON",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 159,
      "type": "platinum",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_16",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_SON",
      "name": "Son Heung-min",
      "countryCode": "KR",
      "snapshotBio": {
        "position": "LW",
        "age": 32,
        "height": 183,
        "weight": 77,
        "games": 550,
        "goals": 190,
        "assists": 85,
      },
    },
    "club": {"id": "CLUB_TOTTENHAM", "name": "Tottenham Hotspur", "country": "GB", "city": "London"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.son,
        "playerCard": "cdn/player/son_card.png",
        "clubImage": ImagePaths.home.tottenham,
        "clubLogo": "cdn/club/tottenham_logo.png",
      },
      "videos": {"goals": "cdn/video/son_goals.mp4"},
    },
    "market": {
      "currentPrice": 130.0,
      "lastTransactionPrice": 125.0,
      "low": 120.0,
      "high": 140.0,
      "currency": "EUR",
      "trend": 8.63,
      "isUp": true,
      "floorPrice": 120.0,
      "highestBid": 125.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Harry Kane
  {
    "id": "UUID_KANE",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 160,
      "type": "gold",
      "class": "S",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_17",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_KANE",
      "name": "Harry Kane",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "CF",
        "age": 31,
        "height": 188,
        "weight": 86,
        "games": 620,
        "goals": 380,
        "assists": 90,
      },
    },
    "club": {"id": "CLUB_BAYERN", "name": "Bayern Munich", "country": "DE", "city": "Munich"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.kane,
        "playerCard": "cdn/player/kane_card.png",
        "clubImage": ImagePaths.home.bayern,
        "clubLogo": "cdn/club/bayern_logo.png",
      },
      "videos": {"goals": "cdn/video/kane_goals.mp4"},
    },
    "market": {
      "currentPrice": 155.0,
      "lastTransactionPrice": 150.0,
      "low": 145.0,
      "high": 160.0,
      "currency": "EUR",
      "trend": 14.52,
      "isUp": true,
      "floorPrice": 145.0,
      "highestBid": 150.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Mason Mount
  {
    "id": "UUID_MOUNT",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 161,
      "type": "bronze",
      "class": "C",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_18",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_MOUNT",
      "name": "Mason Mount",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "CM",
        "age": 25,
        "height": 181,
        "weight": 74,
        "games": 260,
        "goals": 38,
        "assists": 35,
      },
    },
    "club": {"id": "CLUB_MANCHESTER", "name": "Manchester United", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.mount,
        "playerCard": "cdn/player/mount_card.png",
        "clubImage": ImagePaths.home.manchesterUnited,
        "clubLogo": "cdn/club/manchester_logo.png",
      },
      "videos": {"goals": "cdn/video/mount_goals.mp4"},
    },
    "market": {
      "currentPrice": 90.0,
      "lastTransactionPrice": 85.0,
      "low": 80.0,
      "high": 95.0,
      "currency": "EUR",
      "trend": -7.32,
      "isUp": false,
      "floorPrice": 80.0,
      "highestBid": 85.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Kai Havertz
  {
    "id": "UUID_HAVERTZ",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 162,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_19",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_HAVERTZ",
      "name": "Kai Havertz",
      "countryCode": "DE",
      "snapshotBio": {
        "position": "CAM",
        "age": 25,
        "height": 193,
        "weight": 82,
        "games": 340,
        "goals": 90,
        "assists": 55,
      },
    },
    "club": {"id": "CLUB_ARSENAL", "name": "Arsenal", "country": "GB", "city": "London"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.havertz,
        "playerCard": "cdn/player/havertz_card.png",
        "clubImage": ImagePaths.home.arsenal,
        "clubLogo": "cdn/club/arsenal_logo.png",
      },
      "videos": {"goals": "cdn/video/havertz_goals.mp4"},
    },
    "market": {
      "currentPrice": 100.0,
      "lastTransactionPrice": 95.0,
      "low": 90.0,
      "high": 105.0,
      "currency": "EUR",
      "trend": 1.74,
      "isUp": true,
      "floorPrice": 90.0,
      "highestBid": 95.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Raheem Sterling
  {
    "id": "UUID_STERLING",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 163,
      "type": "silver",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_20",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_STERLING",
      "name": "Raheem Sterling",
      "countryCode": "GB",
      "snapshotBio": {
        "position": "LW",
        "age": 29,
        "height": 172,
        "weight": 69,
        "games": 570,
        "goals": 160,
        "assists": 95,
      },
    },
    "club": {"id": "CLUB_CHELSEA", "name": "Chelsea", "country": "GB", "city": "London"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.sterling,
        "playerCard": "cdn/player/sterling_card.png",
        "clubImage": ImagePaths.home.chelsea,
        "clubLogo": "cdn/club/chelsea_logo.png",
      },
      "videos": {"goals": "cdn/video/sterling_goals.mp4"},
    },
    "market": {
      "currentPrice": 95.0,
      "lastTransactionPrice": 90.0,
      "low": 85.0,
      "high": 100.0,
      "currency": "EUR",
      "trend": -4.91,
      "isUp": false,
      "floorPrice": 85.0,
      "highestBid": 90.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Antony
  {
    "id": "UUID_ANTONY",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 164,
      "type": "bronze",
      "class": "C",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_21",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_ANTONY",
      "name": "Antony",
      "countryCode": "BR",
      "snapshotBio": {
        "position": "RW",
        "age": 24,
        "height": 174,
        "weight": 65,
        "games": 190,
        "goals": 28,
        "assists": 25,
      },
    },
    "club": {"id": "CLUB_MANCHESTER_UNITED", "name": "Manchester United", "country": "GB", "city": "Manchester"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.antony,
        "playerCard": "cdn/player/antony_card.png",
        "clubImage": ImagePaths.home.manchesterUnited,
        "clubLogo": "cdn/club/manchester_united_logo.png",
      },
      "videos": {"goals": "cdn/video/antony_goals.mp4"},
    },
    "market": {
      "currentPrice": 80.0,
      "lastTransactionPrice": 75.0,
      "low": 70.0,
      "high": 85.0,
      "currency": "EUR",
      "trend": -5.67,
      "isUp": false,
      "floorPrice": 70.0,
      "highestBid": 75.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Dominik Szoboszlai
  {
    "id": "UUID_SZOBOSZLAI",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 165,
      "type": "bronze",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_21",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_SZOBOSZLAI",
      "name": "Dominik Szoboszlai",
      "countryCode": "HU",
      "snapshotBio": {
        "position": "CAM",
        "age": 23,
        "height": 186,
        "weight": 76,
        "games": 180,
        "goals": 40,
        "assists": 35,
      },
    },
    "club": {"id": "CLUB_LIVERPOOL", "name": "Liverpool", "country": "GB", "city": "Liverpool"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.szoboszlai,
        "playerCard": "cdn/player/szoboszlai_card.png",
        "clubImage": ImagePaths.home.liverpool,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/szoboszlai_goals.mp4"},
    },
    "market": {
      "currentPrice": 115.0,
      "lastTransactionPrice": 110.0,
      "low": 105.0,
      "high": 120.0,
      "currency": "EUR",
      "trend": 7.13,
      "isUp": true,
      "floorPrice": 105.0,
      "highestBid": 110.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Diogo Jota
  {
    "id": "UUID_JOTA",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 166,
      "type": "bronze",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_21",
      "approverName": "Kick26 Approver",
      "owned": 1,
    },
    "player": {
      "playerId": "PLAYER_JOTA",
      "name": "Diogo Jota",
      "countryCode": "PT",
      "snapshotBio": {
        "position": "LW",
        "age": 27,
        "height": 178,
        "weight": 70,
        "games": 310,
        "goals": 105,
        "assists": 45,
      },
    },
    "club": {"id": "CLUB_LIVERPOOL", "name": "Liverpool", "country": "GB", "city": "Liverpool"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.jota,
        "playerCard": "cdn/player/jota_card.png",
        "clubImage": ImagePaths.home.liverpool,
        "clubLogo": "cdn/club/liverpool_logo.png",
      },
      "videos": {"goals": "cdn/video/jota_goals.mp4"},
    },
    "market": {
      "currentPrice": 105.0,
      "lastTransactionPrice": 100.0,
      "low": 95.0,
      "high": 110.0,
      "currency": "EUR",
      "trend": 3.65,
      "isUp": true,
      "floorPrice": 95.0,
      "highestBid": 100.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Ousmane Dembélé
  {
    "id": "UUID_DEMBELE",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 167,
      "type": "bronze",
      "class": "B",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_22",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_DEMBELE",
      "name": "Ousmane Dembélé",
      "countryCode": "FR",
      "snapshotBio": {
        "position": "RW",
        "age": 27,
        "height": 178,
        "weight": 73,
        "games": 280,
        "goals": 50,
        "assists": 70,
      },
    },
    "club": {"id": "CLUB_PSG", "name": "PSG", "country": "FR", "city": "Paris"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.dembele,
        "playerCard": "cdn/player/dembele_card.png",
        "clubImage": ImagePaths.home.psg,
        "clubLogo": "cdn/club/psg_logo.png",
      },
      "videos": {"goals": "cdn/video/dembele_goals.mp4"},
    },
    "market": {
      "currentPrice": 110.0,
      "lastTransactionPrice": 105.0,
      "low": 100.0,
      "high": 115.0,
      "currency": "EUR",
      "trend": 5.92,
      "isUp": true,
      "floorPrice": 100.0,
      "highestBid": 105.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Achraf Hakimi
  {
    "id": "UUID_HAKIMI",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 168,
      "type": "platinum",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_23",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_HAKIMI",
      "name": "Achraf Hakimi",
      "countryCode": "MA",
      "snapshotBio": {
        "position": "RB",
        "age": 26,
        "height": 181,
        "weight": 73,
        "games": 330,
        "goals": 38,
        "assists": 55,
      },
    },
    "club": {"id": "CLUB_PSG", "name": "PSG", "country": "FR", "city": "Paris"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.hakimi,
        "playerCard": "cdn/player/hakimi_card.png",
        "clubImage": ImagePaths.home.psg,
        "clubLogo": "cdn/club/psg_logo.png",
      },
      "videos": {"goals": "cdn/video/hakimi_goals.mp4"},
    },
    "market": {
      "currentPrice": 135.0,
      "lastTransactionPrice": 130.0,
      "low": 125.0,
      "high": 140.0,
      "currency": "EUR",
      "trend": 2.14,
      "isUp": true,
      "floorPrice": 125.0,
      "highestBid": 130.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Theo Hernández
  {
    "id": "UUID_HERNANDEZ",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 169,
      "type": "platinum",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_24",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_HERNANDEZ",
      "name": "Theo Hernández",
      "countryCode": "FR",
      "snapshotBio": {
        "position": "LB",
        "age": 26,
        "height": 184,
        "weight": 78,
        "games": 320,
        "goals": 28,
        "assists": 32,
      },
    },
    "club": {"id": "CLUB_AC_MILAN", "name": "AC Milan", "country": "IT", "city": "Milan"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.hernandez,
        "playerCard": "cdn/player/hernandez_card.png",
        "clubImage": ImagePaths.home.milan,
        "clubLogo": "cdn/club/milan_logo.png",
      },
      "videos": {"goals": "cdn/video/hernandez_goals.mp4"},
    },
    "market": {
      "currentPrice": 130.0,
      "lastTransactionPrice": 125.0,
      "low": 120.0,
      "high": 135.0,
      "currency": "EUR",
      "trend": 6.23,
      "isUp": true,
      "floorPrice": 120.0,
      "highestBid": 125.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },

  // Eduardo Camavinga
  {
    "id": "UUID_CAMAVINGA",
    "data": {
      "edition": "2024",
      "totalIssued": 1000,
      "sequenceNumber": 170,
      "type": "platinum",
      "class": "A",
      "issuedAt": "2024-10-15T09:00:00Z",
      "issuerId": "KICK26_PLATFORM",
      "issuerName": "Kick26 Official",
      "approverId": "APPROVER_25",
      "approverName": "Kick26 Approver",
      "owned": 0,
    },
    "player": {
      "playerId": "PLAYER_CAMAVINGA",
      "name": "Eduardo Camavinga",
      "countryCode": "FR",
      "snapshotBio": {
        "position": "CM",
        "age": 21,
        "height": 182,
        "weight": 68,
        "games": 160,
        "goals": 6,
        "assists": 12,
      },
    },
    "club": {"id": "CLUB_REAL_MADRID", "name": "Real Madrid", "country": "ES", "city": "Madrid"},
    "media": {
      "images": {
        "playerProfile": ImagePaths.home.camavinga,
        "playerCard": "cdn/player/camavinga_card.png",
        "clubImage": ImagePaths.home.realMadrid,
        "clubLogo": "cdn/club/real_madrid_logo.png",
      },
      "videos": {"goals": "cdn/video/camavinga_goals.mp4"},
    },
    "market": {
      "currentPrice": 125.0,
      "lastTransactionPrice": 120.0,
      "low": 115.0,
      "high": 130.0,
      "currency": "EUR",
      "trend": 9.42,
      "isUp": true,
      "floorPrice": 115.0,
      "highestBid": 120.0,
      "totalTrades": 3,
      "uniqueOwners": 3,
      "isOnMarket": true,
      "isTradable": true,
      "isBidEnabled": true,
      "lastTradedAt": "2025-01-15T16:00:00Z",
    },
    "transactions": [],
    "metadata": {
      "card": {"rarity": 3.2, "popularity": 4.3},
      "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
      "club": {
        "lastUpdated": "2024-12-12T10:15:30Z",
        "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
      },
    },
  },
];
