// import 'package:kick26/src/common/image_paths.dart';
// import 'package:uuid/uuid.dart';

// final Map<String, dynamic> dummyCard = {
//   "id": "cardID",
//   "card": {
//     "edition": "2024",
//     "totalIssued": 100,
//     "sequenceNumber": 1,
//     "type": "silver",
//     "class": "B",
//     "issuedAt": "2024-12-12T10:15:30Z",
//     "issuerId": "KICK26_PLATFORM",
//     "issuerName": "Kick26 Official",
//     "approverId": "1234567890",
//     "approverName": "Kick26 Approver",
//     "owned": 1,
//   },
//   "player": {
//     "playerId": "playerID",
//     "name": "Trent Alexander-Arnold",
//     "countryCode": "GB",
//     "snapshotBio": {"position": "RB", "age": 25, "height": 175, "weight": 69, "games": 320, "goals": 18, "assists": 81},
//   },
//   "club": {"id": "123456789", "name": "Liverpool", "country": "GB", "city": "Liverpool"},
//   "media": {
//     "images": {
//       "playerProfile": "cdn/player/trent_profile.png",
//       "playerCard": "cdn/player/trent_card.png",
//       "clubImage": "cdn/club/liverpool_stadium.png",
//       "clubLogo": "cdn/club/liverpool_logo.png",
//     },
//     "videos": {"goals": "cdn/video/trent_goals.mp4"},
//   },
//   "market": {
//     "currentPrice": 105.0,
//     "lastTransactionPrice": 102.5,
//     "low": 98.0,
//     "high": 105.0,
//     "currency": "EUR",
//     "trend": 4.25,
//     "isUp": true,
//     "floorPrice": 98.0,
//     "highestBid": 104.25,
//     "totalTrades": 3,
//     "uniqueOwners": 3,
//     "isOnMarket": true,
//     "isTradable": true,
//     "isBidEnabled": true,
//     "lastTradedAt": "2025-02-14T09:30:00Z",
//   },
//   "transactions": [
//     {
//       "type": "mint",
//       "timestamp": "2024-12-12T10:15:30Z",
//       "price": 100.0,
//       "priceDelta": 0,
//       "seller": null,
//       "buyer": {"id": "KICK26_PLATFORM", "name": "Kick26 Official", "icon": "cdn/platform.png"},
//     },
//     {
//       "type": "sale",
//       "timestamp": "2024-12-15T14:20:00Z",
//       "price": 98.5,
//       "priceDelta": -1.1,
//       "seller": {"id": "USER_89342", "name": "Alex Morgan", "icon": "cdn/user/alex.png"},
//       "buyer": {"id": "USER_47211", "name": "Jan Goed", "icon": "cdn/user/jan.png"},
//     },
//   ],
//   "metadata": {
//     "card": {"rarity": 2.3, "popularity": 4.9},
//     "player": {"lastUpdated": "2024-12-12T10:15:30Z"},
//     "club": {
//       "lastUpdated": "2024-12-12T10:15:30Z",
//       "match": {"last": "cdn/match/last.json", "upcoming": "cdn/match/upcoming.json", "highlights": null},
//     },
//   },
// };

// final List<Map<String, dynamic>> dummyPlayers = [
//   {
//     'id': Uuid().v4(),
//     'name': 'Trent Alexander-Arnold',
//     'price': '€105.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 1,
//     'club': 'Liverpool',
//     'image': ImagePaths.home.trent,
//     'clubImage': ImagePaths.home.liverpool,
//     'trend': 4.25,
//     'isUp': true,
//     'countryCode': 'GB',
//     'height': 175,
//     'weight': 69,
//     'age': 25,
//     'games': 320,
//     'goals': 18,
//     'assists': 81,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Kylian Mbappé',
//     'price': '€190.00',
//     'totalCards': 1000,
//     'cardClass': 'S',
//     'owned': 1,
//     'club': 'Real Madrid',
//     'image': ImagePaths.home.mbappe,
//     'clubImage': ImagePaths.home.realMadrid,
//     'trend': 42.35,
//     'isUp': true,
//     'countryCode': 'FR',
//     'height': 178,
//     'weight': 75,
//     'age': 25,
//     'games': 350,
//     'goals': 270,
//     'assists': 110,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Viktor Gyökeres',
//     'price': '€115.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Sporting CP',
//     'image': ImagePaths.home.gyokeres,
//     'clubImage': ImagePaths.home.sporting,
//     'trend': 3.12,
//     'isUp': true,
//     'countryCode': 'SE',
//     'height': 187,
//     'weight': 86,
//     'age': 26,
//     'games': 240,
//     'goals': 105,
//     'assists': 40,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Julián Álvarez',
//     'price': '€120.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Manchester City',
//     'image': ImagePaths.home.alvarez,
//     'clubImage': ImagePaths.home.manchesterCity,
//     'trend': 7.45,
//     'isUp': true,
//     'countryCode': 'AR',
//     'height': 170,
//     'weight': 71,
//     'age': 24,
//     'games': 210,
//     'goals': 92,
//     'assists': 35,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Erling Haaland',
//     'price': '€185.00',
//     'totalCards': 1000,
//     'cardClass': 'S',
//     'owned': 1,
//     'club': 'Manchester City',
//     'image': ImagePaths.home.haaland,
//     'clubImage': ImagePaths.home.manchesterCity,
//     'trend': 18.22,
//     'isUp': true,
//     'countryCode': 'NO',
//     'height': 194,
//     'weight': 94,
//     'age': 24,
//     'games': 240,
//     'goals': 210,
//     'assists': 45,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Vinícius Jr',
//     'price': '€155.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 1,
//     'club': 'Real Madrid',
//     'image': ImagePaths.home.vinicius,
//     'clubImage': ImagePaths.home.realMadrid,
//     'trend': 15.67,
//     'isUp': true,
//     'countryCode': 'BR',
//     'height': 176,
//     'weight': 73,
//     'age': 23,
//     'games': 260,
//     'goals': 75,
//     'assists': 70,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Bukayo Saka',
//     'price': '€145.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 1,
//     'club': 'Arsenal',
//     'image': ImagePaths.home.saka,
//     'clubImage': ImagePaths.home.arsenal,
//     'trend': 12.85,
//     'isUp': true,
//     'countryCode': 'GB',
//     'height': 178,
//     'weight': 72,
//     'age': 22,
//     'games': 220,
//     'goals': 58,
//     'assists': 51,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Pedri González',
//     'price': '€125.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'FC Barcelona',
//     'image': ImagePaths.home.pedri,
//     'clubImage': ImagePaths.home.fcb,
//     'trend': -2.15,
//     'isUp': false,
//     'countryCode': 'ES',
//     'height': 174,
//     'weight': 62,
//     'age': 21,
//     'games': 160,
//     'goals': 18,
//     'assists': 20,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Florian Wirtz',
//     'price': '€150.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Bayer Leverkusen',
//     'image': ImagePaths.home.wirtz,
//     'clubImage': ImagePaths.home.leverkusen,
//     'trend': 9.48,
//     'isUp': true,
//     'countryCode': 'DE',
//     'height': 176,
//     'weight': 70,
//     'age': 21,
//     'games': 150,
//     'goals': 35,
//     'assists': 40,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Jude Bellingham',
//     'price': '€180.00',
//     'totalCards': 1000,
//     'cardClass': 'S',
//     'owned': 0,
//     'club': 'Real Madrid',
//     'image': ImagePaths.home.bellingham,
//     'clubImage': ImagePaths.home.realMadrid,
//     'trend': 25.75,
//     'isUp': true,
//     'countryCode': 'GB',
//     'height': 186,
//     'weight': 75,
//     'age': 21,
//     'games': 200,
//     'goals': 55,
//     'assists': 30,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Phil Foden',
//     'price': '€135.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Manchester City',
//     'image': ImagePaths.home.foden,
//     'clubImage': ImagePaths.home.manchesterCity,
//     'trend': 10.25,
//     'isUp': true,
//     'countryCode': 'GB',
//     'height': 171,
//     'weight': 70,
//     'age': 23,
//     'games': 260,
//     'goals': 65,
//     'assists': 45,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Lautaro Martínez',
//     'price': '€125.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Inter Milan',
//     'image': ImagePaths.home.martinez,
//     'clubImage': ImagePaths.home.inter,
//     'trend': 6.52,
//     'isUp': true,
//     'countryCode': 'AR',
//     'height': 174,
//     'weight': 72,
//     'age': 26,
//     'games': 280,
//     'goals': 150,
//     'assists': 50,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Khvicha Kvaratskhelia',
//     'price': '€140.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Napoli',
//     'image': ImagePaths.home.kvaratskhelia,
//     'clubImage': ImagePaths.home.napoli,
//     'trend': -1.84,
//     'isUp': false,
//     'countryCode': 'GE',
//     'height': 183,
//     'weight': 76,
//     'age': 23,
//     'games': 170,
//     'goals': 45,
//     'assists': 50,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Rafael Leão',
//     'price': '€130.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'AC Milan',
//     'image': ImagePaths.home.leao,
//     'clubImage': ImagePaths.home.milan,
//     'trend': 8.35,
//     'isUp': true,
//     'countryCode': 'PT',
//     'height': 188,
//     'weight': 81,
//     'age': 24,
//     'games': 240,
//     'goals': 65,
//     'assists': 55,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Jamal Musiala',
//     'price': '€165.00',
//     'totalCards': 1000,
//     'cardClass': 'S',
//     'owned': 0,
//     'club': 'Bayern Munich',
//     'image': ImagePaths.home.musiala,
//     'clubImage': ImagePaths.home.bayern,
//     'trend': 6.72,
//     'isUp': true,
//     'countryCode': 'DE',
//     'height': 183,
//     'weight': 70,
//     'age': 21,
//     'games': 170,
//     'goals': 40,
//     'assists': 30,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Rodrygo Goes',
//     'price': '€120.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Real Madrid',
//     'image': ImagePaths.home.rodrygo,
//     'clubImage': ImagePaths.home.realMadrid,
//     'trend': 5.42,
//     'isUp': true,
//     'countryCode': 'BR',
//     'height': 174,
//     'weight': 70,
//     'age': 23,
//     'games': 210,
//     'goals': 48,
//     'assists': 35,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Martin Ødegaard',
//     'price': '€135.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Arsenal',
//     'image': ImagePaths.home.odegaard,
//     'clubImage': ImagePaths.home.arsenal,
//     'trend': 9.64,
//     'isUp': true,
//     'countryCode': 'NO',
//     'height': 178,
//     'weight': 68,
//     'age': 25,
//     'games': 300,
//     'goals': 70,
//     'assists': 80,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'João Félix',
//     'price': '€95.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'FC Barcelona',
//     'image': ImagePaths.home.felix,
//     'clubImage': ImagePaths.home.fcb,
//     'trend': -4.38,
//     'isUp': false,
//     'countryCode': 'PT',
//     'height': 181,
//     'weight': 70,
//     'age': 24,
//     'games': 220,
//     'goals': 60,
//     'assists': 40,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Gavi',
//     'price': '€110.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'FC Barcelona',
//     'image': ImagePaths.home.gavi,
//     'clubImage': ImagePaths.home.fcb,
//     'trend': 3.47,
//     'isUp': true,
//     'countryCode': 'ES',
//     'height': 173,
//     'weight': 68,
//     'age': 20,
//     'games': 130,
//     'goals': 10,
//     'assists': 12,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Marcus Rashford',
//     'price': '€105.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Manchester United',
//     'image': ImagePaths.home.rashford,
//     'clubImage': ImagePaths.home.manchesterUnited,
//     'trend': -5.26,
//     'isUp': false,
//     'countryCode': 'GB',
//     'height': 186,
//     'weight': 78,
//     'age': 26,
//     'games': 370,
//     'goals': 130,
//     'assists': 70,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Leroy Sané',
//     'price': '€100.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Bayern Munich',
//     'image': ImagePaths.home.sane,
//     'clubImage': ImagePaths.home.bayern,
//     'trend': 4.95,
//     'isUp': true,
//     'countryCode': 'DE',
//     'height': 183,
//     'weight': 75,
//     'age': 28,
//     'games': 310,
//     'goals': 90,
//     'assists': 80,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Ferran Torres',
//     'price': '€90.00',
//     'totalCards': 1000,
//     'cardClass': 'C',
//     'owned': 0,
//     'club': 'FC Barcelona',
//     'image': ImagePaths.home.ferran,
//     'clubImage': ImagePaths.home.fcb,
//     'trend': -2.78,
//     'isUp': false,
//     'countryCode': 'ES',
//     'height': 184,
//     'weight': 77,
//     'age': 24,
//     'games': 200,
//     'goals': 43,
//     'assists': 25,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Federico Valverde',
//     'price': '€145.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Real Madrid',
//     'image': ImagePaths.home.valverde,
//     'clubImage': ImagePaths.home.realMadrid,
//     'trend': 8.12,
//     'isUp': true,
//     'countryCode': 'UY',
//     'height': 182,
//     'weight': 78,
//     'age': 25,
//     'games': 260,
//     'goals': 32,
//     'assists': 40,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Declan Rice',
//     'price': '€135.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Arsenal',
//     'image': ImagePaths.home.rice,
//     'clubImage': ImagePaths.home.arsenal,
//     'trend': 5.98,
//     'isUp': true,
//     'countryCode': 'GB',
//     'height': 185,
//     'weight': 80,
//     'age': 25,
//     'games': 300,
//     'goals': 18,
//     'assists': 20,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Enzo Fernández',
//     'price': '€115.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Chelsea',
//     'image': ImagePaths.home.enzo,
//     'clubImage': ImagePaths.home.chelsea,
//     'trend': -3.12,
//     'isUp': false,
//     'countryCode': 'AR',
//     'height': 178,
//     'weight': 73,
//     'age': 23,
//     'games': 150,
//     'goals': 12,
//     'assists': 18,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Christopher Nkunku',
//     'price': '€110.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Chelsea',
//     'image': ImagePaths.home.nkunku,
//     'clubImage': ImagePaths.home.chelsea,
//     'trend': 2.54,
//     'isUp': true,
//     'countryCode': 'FR',
//     'height': 175,
//     'weight': 69,
//     'age': 27,
//     'games': 260,
//     'goals': 105,
//     'assists': 60,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Alejandro Garnacho',
//     'price': '€95.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Manchester United',
//     'image': ImagePaths.home.garnacho,
//     'clubImage': ImagePaths.home.manchesterUnited,
//     'trend': 10.15,
//     'isUp': true,
//     'countryCode': 'AR',
//     'height': 180,
//     'weight': 75,
//     'age': 20,
//     'games': 80,
//     'goals': 15,
//     'assists': 12,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Nico Williams',
//     'price': '€105.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Athletic Bilbao',
//     'image': ImagePaths.home.nico,
//     'clubImage': ImagePaths.home.bilbao,
//     'trend': 4.62,
//     'isUp': true,
//     'countryCode': 'ES',
//     'height': 181,
//     'weight': 72,
//     'age': 21,
//     'games': 150,
//     'goals': 25,
//     'assists': 30,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Xavi Simons',
//     'price': '€120.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'RB Leipzig',
//     'image': ImagePaths.home.simons,
//     'clubImage': ImagePaths.home.rbl,
//     'trend': 12.38,
//     'isUp': true,
//     'countryCode': 'NL',
//     'height': 179,
//     'weight': 71,
//     'age': 21,
//     'games': 120,
//     'goals': 25,
//     'assists': 35,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Rasmus Højlund',
//     'price': '€85.00',
//     'totalCards': 1000,
//     'cardClass': 'C',
//     'owned': 1,
//     'club': 'Manchester United',
//     'image': ImagePaths.home.hojlund,
//     'clubImage': ImagePaths.home.manchesterUnited,
//     'trend': 6.41,
//     'isUp': true,
//     'countryCode': 'DK',
//     'height': 191,
//     'weight': 84,
//     'age': 21,
//     'games': 110,
//     'goals': 32,
//     'assists': 10,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Frenkie de Jong',
//     'price': '€125.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'FC Barcelona',
//     'image': ImagePaths.home.dejong,
//     'clubImage': ImagePaths.home.fcb,
//     'trend': -1.92,
//     'isUp': false,
//     'countryCode': 'NL',
//     'height': 181,
//     'weight': 74,
//     'age': 27,
//     'games': 340,
//     'goals': 23,
//     'assists': 30,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Joshua Kimmich',
//     'price': '€130.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Bayern Munich',
//     'image': ImagePaths.home.kimmich,
//     'clubImage': ImagePaths.home.bayern,
//     'trend': 2.73,
//     'isUp': true,
//     'countryCode': 'DE',
//     'height': 177,
//     'weight': 72,
//     'age': 29,
//     'games': 410,
//     'goals': 48,
//     'assists': 90,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Casemiro',
//     'price': '€95.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Manchester United',
//     'image': ImagePaths.home.casemiro,
//     'clubImage': ImagePaths.home.manchesterUnited,
//     'trend': -3.88,
//     'isUp': false,
//     'countryCode': 'BR',
//     'height': 185,
//     'weight': 84,
//     'age': 32,
//     'games': 520,
//     'goals': 55,
//     'assists': 40,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Sandro Tonali',
//     'price': '€100.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Newcastle United',
//     'image': ImagePaths.home.tonali,
//     'clubImage': ImagePaths.home.newcastle,
//     'trend': -6.74,
//     'isUp': false,
//     'countryCode': 'IT',
//     'height': 181,
//     'weight': 79,
//     'age': 23,
//     'games': 210,
//     'goals': 15,
//     'assists': 22,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Bernardo Silva',
//     'price': '€140.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Manchester City',
//     'image': ImagePaths.home.bernardo,
//     'clubImage': ImagePaths.home.manchesterCity,
//     'trend': 3.45,
//     'isUp': true,
//     'countryCode': 'PT',
//     'height': 173,
//     'weight': 64,
//     'age': 29,
//     'games': 520,
//     'goals': 80,
//     'assists': 95,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Jack Grealish',
//     'price': '€110.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Manchester City',
//     'image': ImagePaths.home.grealish,
//     'clubImage': ImagePaths.home.manchesterCity,
//     'trend': -1.24,
//     'isUp': false,
//     'countryCode': 'GB',
//     'height': 180,
//     'weight': 75,
//     'age': 28,
//     'games': 340,
//     'goals': 55,
//     'assists': 50,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Bruno Fernandes',
//     'price': '€120.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 1,
//     'club': 'Manchester United',
//     'image': ImagePaths.home.bruno,
//     'clubImage': ImagePaths.home.manchesterUnited,
//     'trend': 5.26,
//     'isUp': true,
//     'countryCode': 'PT',
//     'height': 179,
//     'weight': 69,
//     'age': 29,
//     'games': 430,
//     'goals': 135,
//     'assists': 120,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Mohamed Salah',
//     'price': '€150.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Liverpool',
//     'image': ImagePaths.home.salah,
//     'clubImage': ImagePaths.home.liverpool,
//     'trend': 11.24,
//     'isUp': true,
//     'countryCode': 'EG',
//     'height': 175,
//     'weight': 74,
//     'age': 32,
//     'games': 620,
//     'goals': 290,
//     'assists': 140,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Darwin Núñez',
//     'price': '€85.00',
//     'totalCards': 1000,
//     'cardClass': 'C',
//     'owned': 0,
//     'club': 'Liverpool',
//     'image': ImagePaths.home.nunez,
//     'clubImage': ImagePaths.home.liverpool,
//     'trend': 3.15,
//     'isUp': true,
//     'countryCode': 'UY',
//     'height': 187,
//     'weight': 81,
//     'age': 25,
//     'games': 170,
//     'goals': 70,
//     'assists': 20,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Son Heung-min',
//     'price': '€130.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Tottenham Hotspur',
//     'image': ImagePaths.home.son,
//     'clubImage': ImagePaths.home.tottenham,
//     'trend': 8.63,
//     'isUp': true,
//     'countryCode': 'KR',
//     'height': 183,
//     'weight': 77,
//     'age': 32,
//     'games': 550,
//     'goals': 190,
//     'assists': 85,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Harry Kane',
//     'price': '€155.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Bayern Munich',
//     'image': ImagePaths.home.kane,
//     'clubImage': ImagePaths.home.bayern,
//     'trend': 14.52,
//     'isUp': true,
//     'countryCode': 'GB',
//     'height': 188,
//     'weight': 86,
//     'age': 31,
//     'games': 620,
//     'goals': 380,
//     'assists': 90,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Mason Mount',
//     'price': '€90.00',
//     'totalCards': 1000,
//     'cardClass': 'C',
//     'owned': 0,
//     'club': 'Manchester United',
//     'image': ImagePaths.home.mount,
//     'clubImage': ImagePaths.home.manchesterUnited,
//     'trend': -7.32,
//     'isUp': false,
//     'countryCode': 'GB',
//     'height': 181,
//     'weight': 74,
//     'age': 25,
//     'games': 260,
//     'goals': 38,
//     'assists': 35,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Kai Havertz',
//     'price': '€100.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 1,
//     'club': 'Arsenal',
//     'image': ImagePaths.home.havertz,
//     'clubImage': ImagePaths.home.arsenal,
//     'trend': 1.74,
//     'isUp': true,
//     'countryCode': 'DE',
//     'height': 193,
//     'weight': 82,
//     'age': 25,
//     'games': 340,
//     'goals': 90,
//     'assists': 55,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Raheem Sterling',
//     'price': '€95.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'Chelsea',
//     'image': ImagePaths.home.sterling,
//     'clubImage': ImagePaths.home.chelsea,
//     'trend': -4.91,
//     'isUp': false,
//     'countryCode': 'GB',
//     'height': 172,
//     'weight': 69,
//     'age': 29,
//     'games': 570,
//     'goals': 160,
//     'assists': 95,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Antony',
//     'price': '€80.00',
//     'totalCards': 1000,
//     'cardClass': 'C',
//     'owned': 1,
//     'club': 'Manchester United',
//     'image': ImagePaths.home.antony,
//     'clubImage': ImagePaths.home.manchesterUnited,
//     'trend': -5.67,
//     'isUp': false,
//     'countryCode': 'BR',
//     'height': 174,
//     'weight': 65,
//     'age': 24,
//     'games': 190,
//     'goals': 28,
//     'assists': 25,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Dominik Szoboszlai',
//     'price': '€115.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 1,
//     'club': 'Liverpool',
//     'image': ImagePaths.home.szoboszlai,
//     'clubImage': ImagePaths.home.liverpool,
//     'trend': 7.13,
//     'isUp': true,
//     'countryCode': 'HU',
//     'height': 186,
//     'weight': 76,
//     'age': 23,
//     'games': 180,
//     'goals': 40,
//     'assists': 35,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Diogo Jota',
//     'price': '€105.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 1,
//     'club': 'Liverpool',
//     'image': ImagePaths.home.jota,
//     'clubImage': ImagePaths.home.liverpool,
//     'trend': 3.65,
//     'isUp': true,
//     'countryCode': 'PT',
//     'height': 178,
//     'weight': 70,
//     'age': 27,
//     'games': 310,
//     'goals': 105,
//     'assists': 45,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Ousmane Dembélé',
//     'price': '€110.00',
//     'totalCards': 1000,
//     'cardClass': 'B',
//     'owned': 0,
//     'club': 'PSG',
//     'image': ImagePaths.home.dembele,
//     'clubImage': ImagePaths.home.psg,
//     'trend': 5.92,
//     'isUp': true,
//     'countryCode': 'FR',
//     'height': 178,
//     'weight': 73,
//     'age': 27,
//     'games': 280,
//     'goals': 50,
//     'assists': 70,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Achraf Hakimi',
//     'price': '€135.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'PSG',
//     'image': ImagePaths.home.hakimi,
//     'clubImage': ImagePaths.home.psg,
//     'trend': 2.14,
//     'isUp': true,
//     'countryCode': 'MA',
//     'height': 181,
//     'weight': 73,
//     'age': 26,
//     'games': 330,
//     'goals': 38,
//     'assists': 55,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Theo Hernández',
//     'price': '€130.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'AC Milan',
//     'image': ImagePaths.home.hernandez,
//     'clubImage': ImagePaths.home.milan,
//     'trend': 6.23,
//     'isUp': true,
//     'countryCode': 'FR',
//     'height': 184,
//     'weight': 78,
//     'age': 26,
//     'games': 320,
//     'goals': 28,
//     'assists': 32,
//   },
//   {
//     'id': Uuid().v4(),
//     'name': 'Eduardo Camavinga',
//     'price': '€125.00',
//     'totalCards': 1000,
//     'cardClass': 'A',
//     'owned': 0,
//     'club': 'Real Madrid',
//     'image': ImagePaths.home.camavinga,
//     'clubImage': ImagePaths.home.realMadrid,
//     'trend': 9.42,
//     'isUp': true,
//     'countryCode': 'FR',
//     'height': 182,
//     'weight': 68,
//     'age': 21,
//     'games': 160,
//     'goals': 6,
//     'assists': 12,
//   },
// ];
